### PR TITLE
Fix tab anchors scroll refs #153601

### PR DESCRIPTION
**Pull request by nileshgulia1**
If we have anchors inside Tabs. Linking to that anchors from a outside page first open the corresponding tab and scrolls down to it.

### CODE REVIEW

**Comment by avoinea** [comment]
@nileshgulia1 it doesn't seem to work:

[Agriculture-and-food-system.webm](https://user-images.githubusercontent.com/323385/233043409-74a0bfd6-7102-4847-8413-1d8ea160f741.webm)

**Comment by nileshgulia1** [comment]
@avoinea This is meant to be used with `volto-anchors` . Just gave a quick try on my local and works as intended. 


https://user-images.githubusercontent.com/22280901/233048511-c0db21bc-41ed-4127-ae7e-b17aca1c9cf3.mp4

**Comment by nileshgulia1** [comment]
I will test it further with staging content.

**Comment by avoinea** [comment]
@nileshgulia1 I think the issue is related to the selected template. In this case: `Accordion responsive`.

Please test with all available variations :wink:

**Pull request merged**
